import type { Settings } from '../types/index.ts';

export const defaultSettings: Settings = {
  fontFamily: 'Noto Serif',
  fontSize: 22,
  lineHeight: 1.6,
  paragraphSpacing: 1,
  verticalParagraphSpacing: 0.5,
  marginH: 32,
  marginV: 32,
  verticalMarginV: 48,
  writingMode: 'horizontal',
  theme: 'light',
  showPinyin: false,
  pinyinPosition: 'over',
  pinyinSize: 12,
  showNumbering: false,
  scriptVariant: 'original',
  lineLength: 35,
  showCedict: true,
  showCvdict: false,
  showMoedict: false,
  dictOrder: ['cedict', 'cvdict', 'moedict'],
  popupFontSize: 15,
  hangingIndent: 0,
  boldText: false,
  fileInfoShown: false,
  ttsVoice: '',
  ttsRate: 1.0,
};
